music_app/config/routes.rb
MusicApp::Application.routes.draw do
  resources :artists
  resources :bands do
    collection do
      get 'search'
    end
    resources :recordings, :only => [:new]
  end
  resources :recordings do
    resources :singles, :only => [:new]
  end
  resources :singles
  root :to => "artists#index"
end

music_app/app/models/artist.rb
class Artist < ActiveRecord::Base
  attr_accessible :name, :band_ids

  has_many :band_artists
  has_many :bands, :through => :band_artists
  # has_many :recordings, :through => :bands

  validates :name, :presence => true
end

music_app/app/models/band.rb
class Band < ActiveRecord::Base
  attr_accessible :name

  has_many :band_artists
  has_many :artists, :through => :band_artists
  has_many :recordings
  validates :name, :presence => true
end

music_app/app/models/band_artist.rb
class BandArtist < ActiveRecord::Base
  attr_accessible :band_id, :artist_id
  belongs_to :artist
  belongs_to :band
  validates :artist, :band, :presence => true
end

music_app/app/models/recording.rb
class Recording < ActiveRecord::Base
  attr_accessible :name, :live, :band_id, :description

  belongs_to :band
  has_many :singles

  validates :name, :live, :presence => true
end

music_app/app/models/single.rb
class Single < ActiveRecord::Base
  attr_accessible :name, :recording_id, :bonus

  belongs_to :recording
  validates :name, :bonus, :presence => true
end

music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

music_app/app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end
  def show
    @artist = Artist.find(params[:id])
  end
  def destroy
    Artist.find(params[:id]).destroy
    redirect_to artists_path
  end
  def new
    @artist = Artist.new
  end
  def edit
    @artist = Artist.find(params[:id])
  end
  def update
    @artist = Artist.find(params[:id])
    @artist.update_attributes(params[:artist])
    redirect_to artist_path(@artist)
  end
  def create
    @artist = Artist.create!(params[:artist])
    redirect_to artists_path(@artist)
  end
end

music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def new
    @band = Band.new
  end
  def show
    @band = Band.find(params[:id])
  end
  def index
    @bands = Band.all
  end
  def create
    @band = Band.create!(params[:band])   #REV you can add validation
    redirect_to band_path(@band)
  end
  def destroy
    @band = Band.find(params[:id])
    @band.destroy
    redirect_to bands_path
  end
  def edit
    @band = Band.find(params[:id])
  end
  def update
    @band = Band.find(params[:id])
    @band.update_attributes(params[:band])
    redirect_to band_path(@band)
  end

  def search
    @bands = Band.where("name LIKE ?", "%#{params[:query]}%")
  end
end

music_app/app/controllers/recordings_controller.rb
class RecordingsController < ApplicationController
  def index
    case params["query"]    #REV good job. all it needs is search now
    when "name"
      @recordings = Recording.order(:name)
    when "band_name"
      @recordings = Recording.includes(:band).order("bands.name")
    else
      @recordings = Recording.all
    end
  end
  def show
    @recording = Recording.includes(:band).find(params[:id])
  end
  def new
    @recording = Recording.new
    @recording.band_id = params[:band_id]
  end
  def create
    @recording = Recording.create!(params[:recording])
    redirect_to recording_path(@recording)
  end
  def edit
    @recording = Recording.find(params[:id])
  end
  def update
    @recording = Recording.find(params[:id])
    @recording.update_attributes(params[:recording])
    redirect_to recording_path(@recording)
  end
  def destroy
    @recording = Recording.find(params[:id])
    @recording.destroy
    redirect_to recordings_path
  end
end

music_app/app/controllers/singles_controller.rb
class SinglesController < ApplicationController
  def new
    @single = Single.new
    @single.recording_id = params[:recording_id]
  end
  def create
    @single = Single.create!(params[:single])
    redirect_to single_path(@single)
  end

  def index
    @singles = Single.all
  end

  def show
    @single = Single.includes(:recording).find(params[:id])
  end

  def edit
    @single = Single.find(params[:id])
  end

  def update
    @single = Single.find(params[:id])
    @single.update_attributes(params[:single])
    redirect_to single_path(@single)
  end

  def destroy
    @single = Single.find(params[:id])
    @single.destroy
    redirect_to singles_path
  end
end

music_app/app/helpers/application_helper.rb
module ApplicationHelper
end

music_app/app/helpers/artists_helper.rb
module ArtistsHelper
end

music_app/app/helpers/bands_helper.rb
module BandsHelper
end

music_app/app/helpers/recordings_helper.rb
module RecordingsHelper
end

music_app/app/helpers/singles_helper.rb
module SinglesHelper
end

music_app/app/views/artists/_form.html.erb
<%= form_for(@artist) do |f| %> <!-- REV: nice use of partials -->
  <%= f.label :name %>
  <%= f.text_field :name %><br>
  <% Band.all.each do |band| %>
    <%=
        check_box_tag(
        "artist[band_ids][]",
        band.id,
        !BandArtist.where(:artist_id => @artist.id, :band_id => band.id).empty?,
        :id => "band_id_#{band.id}"
      )
      %>
  <%= label_tag "band_id_#{band.id}", band.name%>
  <% end %>

  <%= f.submit "Create Artist" %>
<% end %>

music_app/app/views/artists/edit.html.erb
<h3>Edit <%= @artist.name %></h3>
<%= render :partial => 'form' %>

music_app/app/views/artists/index.html.erb
<h3>Artists</h3>
<ul>
<% @artists.each do |artist| %>
  <li><%= link_to artist.name, artist_path(artist) %></li>
<% end %>
</ul>
<%= link_to "Create New Artist", new_artist_path %>

music_app/app/views/artists/new.html.erb
<h3>Create New Artist</h3>
<%= render :partial => 'form' %>

music_app/app/views/artists/show.html.erb
<h3>Name</h3>
<%= @artist.name %>

<p>
  Bands: <%= @artist.bands.map {|band| band.name }.join(", ") %><br>
</p>
<h3>Navigation</h3>
<%#= link_to "All Artists", artists_path %>
<%= link_to "Edit Artist", edit_artist_path(@artist) %>
<%= link_to "Delete Artist", artist_path(@artist), :method => :delete%>

music_app/app/views/bands/_form.html.erb
<%= form_for(@band) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br>

  <% Artist.all.each do |artist| %>
    <%=
        check_box_tag(
        "bandartist[artist_ids][]",
        artist.id,
        !BandArtist.where(:artist_id => artist.id, :band_id => @band.id).empty?,
        :id => "artist_id_#{artist.id}"
      )
      %>
  <%= label_tag "artist_id_#{artist.id}", artist.name%>
  <% end %><br>

  <%= f.submit "Create Band"%>
<% end %>

music_app/app/views/bands/edit.html.erb
<h3>Edit <%= @band.name %></h3>
<%= render :partial => 'form' %>

music_app/app/views/bands/index.html.erb
<h3>Bands</h3>
<ul>
<% @bands.each do |band| %>
<li><%= link_to band.name, band_path(band) %></li>
<% end %>
</ul>

<%= link_to "Create New Band", new_band_path %>

music_app/app/views/bands/new.html.erb
<h3>Create New Band</h3>
<%= render :partial => 'form' %>

music_app/app/views/bands/search.html.erb
<h3>Bands</h3>
<ul>
<% @bands.each do |band| %>
<li><%= link_to band.name, band_path(band) %></li>
<% end %>
</ul>

<%= link_to "Create New Band", new_band_path %>

<form method="get" action= <%= search_bands_path %>>
  <input type = "text" name = "query"/>
  <input type = "submit" value = "Search bands"/>
</form>

music_app/app/views/bands/show.html.erb
<h3>Band: <%= @band.name %></h3>

<p>
  Members:
  <%= @band.artists.map { |artist| artist.name }.join(", ")%><br/>

  Recordings:
  <ul>
  <% @band.recordings.each do |recording| %>
    <li><%= link_to recording.name, recording_path(recording)%></li>
  <% end %>
  </ul>
  <%#= link_to "Add Recording", new_recording_path(recording_id)%>
  <%= link_to "Add Recording", new_band_recording_path(@band)%>
</p>

<br/><br/>
<%#= link_to "All Bands", bands_path %>
<%= link_to "Edit", edit_band_path(@band) %>
<%= link_to "Delete", band_path(@band), :method => :delete%>

music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Music App</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "Music App", '#', class: "logo" %>
          <nav>
            <ul class="nav pull-right">
              <li><%= link_to "Artists", artists_path %></li>
              <li><%= link_to "Bands", bands_path %></li>
              <li><%= link_to "Recordings", recordings_path %></li>
              <li><%= link_to "Singles", singles_path %></li>
            </ul>
          </nav>
        </div>
      </div>
    </header>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

music_app/app/views/recordings/_form.html.erb
<%= form_for(@recording) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br>

  <%= f.label :band_id, "Band" %>
  <%=
    f.select(
      :band_id,
      Band.all.map { |band| [band.name, band.id]}
    )
  %><br>
  <%= f.label :live, "Studio Recording", :value => 0 %>
  <%= f.radio_button :live, 0%><br/>
  <%= f.label :live, "Live", :value => 1 %>
  <%= f.radio_button :live, 1 %><br/>

  <%= f.label :description %>
  <%= f.text_area :description %><br/>
  <%= f.submit "Submit" %>
<% end %>

music_app/app/views/recordings/edit.html.erb
<h3>Edit <%= @recording.name %></h3>
<%= render :partial => "form" %>

music_app/app/views/recordings/index.html.erb
<h3>Recordings</h3>

<ul>
<% @recordings.each do |recording| %>
<li><%= link_to recording.name, recording_path(recording) %></li>
<% end %>
</ul>

<p>
  Sort by:
  <%= link_to "Name", :controller => "recordings", :query => "name"%>
  /
  <%= link_to "Band Name", :controller => "recordings", :query => "band_name"%>
</p>
<%= link_to "Create New Recording", new_recording_path %>

music_app/app/views/recordings/new.html.erb
<h3>Create New Recording</h3>
<%= render :partial => 'form', :locals => {} %>

music_app/app/views/recordings/show.html.erb
<h3>Recording: <%= @recording.name %></h3>
<p>
  Band: <%= @recording.band.name %><br>
  Type: <%= @recording.live == 0 ? "Live" : "Studio" %><br/>
  <%="Description #{@recording.description}" unless @recording.description.nil? %>
<ul>
  <% @recording.singles.each do |single| %>
    <li><%= link_to single.name, single_path(single) %></li>
  <% end %>
</ul>
</p>
<%#= link_to "All Recordings", recordings_path %>
<%= link_to "Add Song", new_recording_single_path(@recording) %>
<%= link_to "Edit", edit_recording_path(@recording)%>
<%= link_to "Delete", recording_path(@recording), :method => :delete %>

music_app/app/views/singles/_form.html.erb
<%= form_for(@single) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br/>

  <%= f.label :recording_id, "Album:" %>
  <%= f.select :recording_id,
                Recording.all.map { |recording| [recording.name, recording.id]}%>
  <br/>
  <%= f.label :bonus, "Bonus", :value => 1 %>
  <%= f.radio_button :bonus, 1 %><br>
  <%= f.label :bonus, "Regular", :value => 0 %>
  <%= f.radio_button :bonus, 0 %><br>

  <%= f.submit "Create Single" %>
<% end %>

music_app/app/views/singles/edit.html.erb
<h3>Edit <%= @single.name%></h3>
<%= render :partial => "form" %>

music_app/app/views/singles/index.html.erb
<h3>Singles</h3>
<ul>
  <% @singles.each do |single| %>
  <li><%= link_to single.name, single_path(single) %></li>
  <% end %>
</ul>
<%= link_to "Create New Single", new_single_path %>

music_app/app/views/singles/new.html.erb
<h3> Create New Single </h3>
<%= render :partial => "form" %>

music_app/app/views/singles/show.html.erb
<h3>Single: <%= @single.name%></h3>
<p>
  Band: <%= @single.recording.name %><br/>
  Track Type: <%= @single.bonus == 0 ? "Regular" : "Bonus" %>
  <br/>
  <%#=link_to "All singles", singles_path %>
  <%=link_to "Edit", edit_single_path %>
  <%=link_to "Delete", singles_path(@single), :method => :delete %>
</p>